const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const source = fs.readFileSync(path.join(__dirname, '../Loungepad/ui/app.js'), 'utf8');
const start = source.indexOf('function askSecureInputInstall(feature)');
const end = source.indexOf('/* A row with a fixed set of values', start);
assert(start >= 0 && end > start);
let prompt = null;
const sent = [];
const context = vm.createContext({ S: {}, send: message => sent.push(message), askConfirm: state => prompt = state });
vm.runInContext(source.slice(start, end), context);
const rows = state => { context.S.secureInput = state; prompt = null; sent.length = 0; return context.secureInputRows(); };
const message = () => JSON.parse(JSON.stringify(sent[0]));

for (const [index, feature] of [[0, 'uac'], [1, 'signIn']]) {
  let items = rows({ installed: false, uacEnabled: false, signInEnabled: false });
  assert.equal(items.length, 2, 'only independent toggles appear before installation');
  items[index].action();
  assert.equal(sent.length, 0, 'installation requires confirmation');
  assert.equal(prompt.yesLabel, 'Install and enable');
  assert.match(prompt.body, /other option stays off/);
  prompt.onYes();
  assert.deepEqual(message(), { cmd: 'setSecureInput', feature, enabled: true, installConfirmed: true });
  items = rows({ installed: true, uacEnabled: true, signInEnabled: true });
  assert.equal(items.length, 3);
  items[index].action();
  assert.equal(prompt, null);
  assert.deepEqual(message(), { cmd: 'setSecureInput', feature, enabled: false });
  assert(!sent.some(m => m.cmd === 'uninstallSecureInput'), 'disable retains the service');
  items = rows({ installed: true, uacEnabled: false, signInEnabled: false });
  items[index].action();
  assert.equal(prompt, null, 're-enable does not reinstall');
  assert.deepEqual(message(), { cmd: 'setSecureInput', feature, enabled: true });
}
let items = rows({ installed: true, uacEnabled: true, signInEnabled: false });
assert.equal(items[0].value, true);
assert.equal(items[1].value, false);
items[2].action();
assert.equal(sent.length, 0, 'uninstall requires confirmation');
assert.equal(prompt.danger, true);
assert.match(prompt.body, /XInputUWPFix/);
assert.match(prompt.body, /navigation will be restored/);
prompt.onYes();
assert.deepEqual(message(), { cmd: 'uninstallSecureInput', confirmed: true });
items = rows({ installed: true, busy: true, state: 'Downloading input service', progress: 42 });
items.forEach(item => { item.action(); item.adjust?.(); });
assert.equal(sent.length, 0);
assert.equal(prompt, null);
assert(items[0].hint.includes('42%'));
assert.match(source, /section: "SECURE DESKTOP INPUT \(beta\)", cat: "advanced"[^\n]*\n\s*rows.push\(\.\.\.secureInputRows\(\)\)/);
assert.match(source, /id: "stats"[^\n]*\n\s*\{ id: "advanced",\s+label: "Advanced" \},\s*\]/);
assert(!source.slice(source.indexOf('section: "STARTUP & LOCK SCREEN"'), source.indexOf('name: "Couch setup guide"')).includes('secureInputRows'));
const onboarding = fs.readFileSync(path.join(__dirname, '../Loungepad/ui/onboarding.js'), 'utf8');
assert.match(onboarding.slice(onboarding.indexOf('  signin()'), onboarding.indexOf('  startup()')), /experimental controller input[\s\S]*Settings → Advanced/);
console.log('PASS: independent secure input toggles, confirmation, uninstall, progress, Advanced placement and onboarding');
